source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XLRefreshSwift_Example', :exclusive => true do
  pod 'XLRefreshSwift', :path => '../'
end

target 'XLRefreshSwift_Tests', :exclusive => true do
  pod 'XLRefreshSwift', :path => '../'

  
end
